apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.pv.cast }}-{{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres/{{ .Values.namespace }}/cast-db
  claimRef:
    namespace:  {{ .Values.namespace }}
    name: {{ .Values.db.cast.pvc }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.pv.movie }}-{{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres/{{ .Values.namespace }}/movie-db
  claimRef:
    namespace:  {{ .Values.namespace }}
    name: {{ .Values.db.movie.pvc }}
