apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.pv }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.pvc }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
