apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cast.service }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.cast.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.cast.port }}
