apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.cast.service }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.db.port }}
    protocol: TCP
    targetPort: {{ .Values.db.port }}
  selector:
    app: {{ .Values.db.cast.name }}
